// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108064220_AgregaPrecioPorLoteYSeedDataCorregido")]
    partial class AgregaPrecioPorLoteYSeedDataCorregido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaRuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CedulaRuc = "0101010101",
                            Correo = "juanp@example.com",
                            Direccion = "Quito Centro",
                            Nombre = "Juan Perez",
                            Telefono = "0991112233"
                        },
                        new
                        {
                            Id = 2,
                            CedulaRuc = "0202020202",
                            Correo = "ana.torres@example.com",
                            Direccion = "Guayaquil Norte",
                            Nombre = "Ana Torres",
                            Telefono = "0988899777"
                        },
                        new
                        {
                            Id = 3,
                            CedulaRuc = "1718192021",
                            Correo = "mena.mario@example.com",
                            Direccion = "Cuenca",
                            Nombre = "Mario Mena",
                            Telefono = "0995556666"
                        },
                        new
                        {
                            Id = 4,
                            CedulaRuc = "2122232425",
                            Correo = "luisa.vera@example.com",
                            Direccion = "Ambato",
                            Nombre = "Luisa Vera",
                            Telefono = "0975532332"
                        },
                        new
                        {
                            Id = 5,
                            CedulaRuc = "3031323334",
                            Correo = "pedro.ruiz@example.com",
                            Direccion = "Manta",
                            Nombre = "Pedro Ruíz",
                            Telefono = "0993459821"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 10,
                            CodigoLote = "LAP202511A",
                            FechaIngreso = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 1200.00m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 10,
                            CodigoLote = "LAP202511B",
                            FechaIngreso = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 1180.50m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 100,
                            CodigoLote = "MOU202510A",
                            FechaIngreso = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 35.50m,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 50,
                            CodigoLote = "MOU202511A",
                            FechaIngreso = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 34.75m,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 25,
                            CodigoLote = "MON202509A",
                            FechaIngreso = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 300.00m,
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 15,
                            CodigoLote = "MON202510B",
                            FechaIngreso = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 295.00m,
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 25,
                            CodigoLote = "IMP202510A",
                            FechaIngreso = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 220.75m,
                            ProductoId = 5
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 50,
                            CodigoLote = "SSD202511A",
                            FechaIngreso = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Precio = 102.99m,
                            ProductoId = 7
                        });
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Laptop Dell XPS",
                            Precio = 1200.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Mouse Logitech",
                            Precio = 35.50m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Monitor Samsung",
                            Precio = 300.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Teclado Mecánico",
                            Precio = 80.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Impresora HP",
                            Precio = 220.75m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Tablet Lenovo",
                            Precio = 400.30m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Disco SSD 1TB",
                            Precio = 100.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Cámara Web",
                            Precio = 60.00m,
                            Stock = 95
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Auriculares",
                            Precio = 45.00m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Speakers Bluetooth",
                            Precio = 70.00m,
                            Stock = 35
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasena = "admin123",
                            NombreUsuario = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Contrasena = "testpass",
                            NombreUsuario = "testuser"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Lote", b =>
                {
                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
