// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108174938_ActualizarModeloCompleto")]
    partial class ActualizarModeloCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaRuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CedulaRuc = "1234567890",
                            Correo = "juan@example.com",
                            Direccion = "Av. Principal 123",
                            Nombre = "Juan Pérez",
                            Telefono = "0999999999"
                        },
                        new
                        {
                            Id = 2,
                            CedulaRuc = "0987654321",
                            Correo = "maria@example.com",
                            Direccion = "Calle Secundaria 456",
                            Nombre = "María García",
                            Telefono = "0988888888"
                        },
                        new
                        {
                            Id = 3,
                            CedulaRuc = "1122334455",
                            Correo = "carlos@example.com",
                            Direccion = "Av. Los Pinos 789",
                            Nombre = "Carlos López",
                            Telefono = "0977777777"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 10,
                            NumeroLote = "LOTE-2025-01",
                            PrecioUnitario = 850.00m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 5,
                            NumeroLote = "LOTE-2025-02",
                            PrecioUnitario = 900.00m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 50,
                            NumeroLote = "LOTE-2025-03",
                            PrecioUnitario = 15.00m,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 30,
                            NumeroLote = "LOTE-2025-04",
                            PrecioUnitario = 45.00m,
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 20,
                            NumeroLote = "LOTE-2025-05",
                            PrecioUnitario = 180.00m,
                            ProductoId = 4
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 25,
                            NumeroLote = "LOTE-2025-06",
                            PrecioUnitario = 89.99m,
                            ProductoId = 5
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 15,
                            NumeroLote = "LOTE-2025-07",
                            PrecioUnitario = 120.00m,
                            ProductoId = 6
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 8,
                            NumeroLote = "LOTE-2025-08",
                            PrecioUnitario = 350.00m,
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 40,
                            NumeroLote = "LOTE-2025-09",
                            PrecioUnitario = 65.00m,
                            ProductoId = 8
                        },
                        new
                        {
                            Id = 10,
                            Cantidad = 12,
                            NumeroLote = "LOTE-2025-10",
                            PrecioUnitario = 220.00m,
                            ProductoId = 9
                        },
                        new
                        {
                            Id = 11,
                            Cantidad = 18,
                            NumeroLote = "LOTE-2025-11",
                            PrecioUnitario = 180.00m,
                            ProductoId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PROD-001",
                            Descripcion = "Laptop 15 pulgadas, 8GB RAM, 256GB SSD",
                            Nombre = "Laptop HP Pavilion"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "PROD-002",
                            Descripcion = "Mouse inalámbrico ergonómico",
                            Nombre = "Mouse Logitech"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PROD-003",
                            Descripcion = "Teclado RGB retroiluminado",
                            Nombre = "Teclado Mecánico"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "PROD-004",
                            Descripcion = "Monitor Full HD IPS",
                            Nombre = "Monitor LG 24\""
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "PROD-005",
                            Descripcion = "Webcam Full HD 1080p",
                            Nombre = "Webcam Logitech C920"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "PROD-006",
                            Descripcion = "Auriculares con cancelación de ruido",
                            Nombre = "Auriculares Sony"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "PROD-007",
                            Descripcion = "Impresora láser monocromática",
                            Nombre = "Impresora HP LaserJet"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "PROD-008",
                            Descripcion = "Almacenamiento portátil USB 3.0",
                            Nombre = "Disco Duro Externo 1TB"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "PROD-009",
                            Descripcion = "Router WiFi dual band",
                            Nombre = "Router TP-Link"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "PROD-010",
                            Descripcion = "Silla ergonómica con soporte lumbar",
                            Nombre = "Silla Gamer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contraseña = "admin123",
                            NombreUsuario = "admin",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Contraseña = "vendedor123",
                            NombreUsuario = "vendedor",
                            Rol = "Vendedor"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Lote", b =>
                {
                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
