// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoCliente")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Av. Principal 123 y Secundaria, Quito",
                            Email = "juan.perez@email.com",
                            Identificacion = "1234567890",
                            IsDeleted = false,
                            NombreRazonSocial = "Juan Pérez García",
                            Telefono = "0999999999",
                            TipoIdentificacion = "CEDULA"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Calle Comercio 456, Edificio Blue, Guayaquil",
                            Email = "ventas@distrimartinez.com",
                            Identificacion = "1234567890001",
                            IsDeleted = false,
                            NombreRazonSocial = "DISTRIBUIDORA MARTINEZ CIA. LTDA.",
                            Telefono = "0988888888",
                            TipoIdentificacion = "RUC"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Hotel Hilton, Habitación 305, Quito",
                            Email = "john.smith@email.com",
                            Identificacion = "USA123456",
                            IsDeleted = false,
                            NombreRazonSocial = "John Smith",
                            Telefono = "0977777777",
                            TipoIdentificacion = "PASAPORTE"
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Urbanización Los Pinos, Mz 5 Villa 10, Cuenca",
                            Email = "maria.lopez@email.com",
                            Identificacion = "0987654321",
                            IsDeleted = false,
                            NombreRazonSocial = "María Fernanda López Torres",
                            Telefono = "0966666666",
                            TipoIdentificacion = "CEDULA"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("IvaLinea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LoteId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesFactura");
                });

            modelBuilder.Entity("Domain.Entities.EventoActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventosActividad");
                });

            modelBuilder.Entity("Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Establecimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Iva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PuntoEmision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Domain.Entities.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroLote")
                        .IsUnique();

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 5,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-001-001-0001234",
                            PrecioUnitario = 850.00m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 3,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-001-001-0001890",
                            PrecioUnitario = 870.00m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 50,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-002-002-0002345",
                            PrecioUnitario = 15.00m,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 30,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-002-002-0002890",
                            PrecioUnitario = 18.00m,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 25,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-003-003-0003456",
                            PrecioUnitario = 20.00m,
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 10,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-004-004-0004567",
                            PrecioUnitario = 180.00m,
                            ProductoId = 4
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 5,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-004-004-0004890",
                            PrecioUnitario = 175.00m,
                            ProductoId = 4
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 8,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-005-005-0005678",
                            PrecioUnitario = 120.00m,
                            ProductoId = 5
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 20,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-006-006-0006789",
                            PrecioUnitario = 55.00m,
                            ProductoId = 6
                        },
                        new
                        {
                            Id = 10,
                            Cantidad = 100,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-007-007-0007890",
                            PrecioUnitario = 8.00m,
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 11,
                            Cantidad = 50,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-007-007-0007999",
                            PrecioUnitario = 7.50m,
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 12,
                            Cantidad = 15,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-008-008-0008901",
                            PrecioUnitario = 35.00m,
                            ProductoId = 8
                        },
                        new
                        {
                            Id = 13,
                            Cantidad = 60,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-009-009-0009012",
                            PrecioUnitario = 5.00m,
                            ProductoId = 9
                        },
                        new
                        {
                            Id = 14,
                            Cantidad = 12,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-010-010-0010123",
                            PrecioUnitario = 25.00m,
                            ProductoId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicaIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioVenta")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AplicaIva = true,
                            Codigo = "PROD-001",
                            Descripcion = "Intel Core i5, 8GB RAM, 256GB SSD",
                            IsDeleted = false,
                            Nombre = "Laptop HP Pavilion 15",
                            PrecioVenta = 1100.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            AplicaIva = true,
                            Codigo = "PROD-002",
                            Descripcion = "Inalámbrico, USB, Gris",
                            IsDeleted = false,
                            Nombre = "Mouse Logitech M185",
                            PrecioVenta = 25.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            AplicaIva = true,
                            Codigo = "PROD-003",
                            Descripcion = "USB, Negro, Español",
                            IsDeleted = false,
                            Nombre = "Teclado Genius KB-110",
                            PrecioVenta = 30.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 4,
                            AplicaIva = true,
                            Codigo = "PROD-004",
                            Descripcion = "Full HD, HDMI, VGA",
                            IsDeleted = false,
                            Nombre = "Monitor Samsung 24 pulgadas",
                            PrecioVenta = 220.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            AplicaIva = true,
                            Codigo = "PROD-005",
                            Descripcion = "Multifunción, WiFi, Color",
                            IsDeleted = false,
                            Nombre = "Impresora HP DeskJet 2775",
                            PrecioVenta = 140.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 6,
                            AplicaIva = true,
                            Codigo = "PROD-006",
                            Descripcion = "USB 3.0, Portátil, Negro",
                            IsDeleted = false,
                            Nombre = "Disco Duro Externo 1TB",
                            PrecioVenta = 80.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 7,
                            AplicaIva = true,
                            Codigo = "PROD-007",
                            Descripcion = "USB 3.0, Alta velocidad",
                            IsDeleted = false,
                            Nombre = "Memoria USB 32GB Kingston",
                            PrecioVenta = 12.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 8,
                            AplicaIva = true,
                            Codigo = "PROD-008",
                            Descripcion = "720p, USB, Micrófono integrado",
                            IsDeleted = false,
                            Nombre = "Webcam Logitech C270",
                            PrecioVenta = 45.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 9,
                            AplicaIva = false,
                            Codigo = "PROD-009",
                            Descripcion = "1080p, Compatible 4K",
                            IsDeleted = false,
                            Nombre = "Cable HDMI 2m",
                            PrecioVenta = 10.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 10,
                            AplicaIva = false,
                            Codigo = "PROD-010",
                            Descripcion = "USB 3.0, Alimentación externa",
                            IsDeleted = false,
                            Nombre = "Hub USB 4 puertos",
                            PrecioVenta = 28.00m,
                            Stock = 12
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.DetalleFactura", b =>
                {
                    b.HasOne("Domain.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId");

                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Lote");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Entities.Factura", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.Lote", b =>
                {
                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
