// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "juan.perez@email.com",
                            Direccion = "Av. Principal 123 y Secundaria, Quito",
                            Identificacion = "1234567890",
                            NombreRazonSocial = "Juan Pérez García",
                            Telefono = "0999999999",
                            TipoIdentificacion = ""
                        },
                        new
                        {
                            Id = 2,
                            Correo = "ventas@distrimartinez.com",
                            Direccion = "Calle Comercio 456, Edificio Blue, Guayaquil",
                            Identificacion = "1234567890001",
                            NombreRazonSocial = "DISTRIBUIDORA MARTINEZ CIA. LTDA.",
                            Telefono = "0988888888",
                            TipoIdentificacion = ""
                        },
                        new
                        {
                            Id = 3,
                            Correo = "john.smith@email.com",
                            Direccion = "Hotel Hilton, Habitación 305, Quito",
                            Identificacion = "USA123456",
                            NombreRazonSocial = "John Smith",
                            Telefono = "0977777777",
                            TipoIdentificacion = ""
                        },
                        new
                        {
                            Id = 4,
                            Correo = "maria.lopez@email.com",
                            Direccion = "Urbanización Los Pinos, Mz 5 Villa 10, Cuenca",
                            Identificacion = "0987654321",
                            NombreRazonSocial = "María Fernanda López Torres",
                            Telefono = "0966666666",
                            TipoIdentificacion = ""
                        });
                });

            modelBuilder.Entity("Domain.Entities.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Lotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 5,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-001-001-0001234",
                            PrecioUnitario = 850.00m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 3,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-001-001-0001890",
                            PrecioUnitario = 870.00m,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 50,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-002-002-0002345",
                            PrecioUnitario = 15.00m,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 30,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-002-002-0002890",
                            PrecioUnitario = 18.00m,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 25,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-003-003-0003456",
                            PrecioUnitario = 20.00m,
                            ProductoId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 10,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-004-004-0004567",
                            PrecioUnitario = 180.00m,
                            ProductoId = 4
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 5,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-004-004-0004890",
                            PrecioUnitario = 175.00m,
                            ProductoId = 4
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 8,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-005-005-0005678",
                            PrecioUnitario = 120.00m,
                            ProductoId = 5
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 20,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-006-006-0006789",
                            PrecioUnitario = 55.00m,
                            ProductoId = 6
                        },
                        new
                        {
                            Id = 10,
                            Cantidad = 100,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-007-007-0007890",
                            PrecioUnitario = 8.00m,
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 11,
                            Cantidad = 50,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-007-007-0007999",
                            PrecioUnitario = 7.50m,
                            ProductoId = 7
                        },
                        new
                        {
                            Id = 12,
                            Cantidad = 15,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-008-008-0008901",
                            PrecioUnitario = 35.00m,
                            ProductoId = 8
                        },
                        new
                        {
                            Id = 13,
                            Cantidad = 60,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-009-009-0009012",
                            PrecioUnitario = 5.00m,
                            ProductoId = 9
                        },
                        new
                        {
                            Id = 14,
                            Cantidad = 12,
                            FechaIngreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "FAC-010-010-0010123",
                            PrecioUnitario = 25.00m,
                            ProductoId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PROD-001",
                            Descripcion = "Intel Core i5, 8GB RAM, 256GB SSD",
                            Nombre = "Laptop HP Pavilion 15"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "PROD-002",
                            Descripcion = "Inalámbrico, USB, Gris",
                            Nombre = "Mouse Logitech M185"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PROD-003",
                            Descripcion = "USB, Negro, Español",
                            Nombre = "Teclado Genius KB-110"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "PROD-004",
                            Descripcion = "Full HD, HDMI, VGA",
                            Nombre = "Monitor Samsung 24 pulgadas"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "PROD-005",
                            Descripcion = "Multifunción, WiFi, Color",
                            Nombre = "Impresora HP DeskJet 2775"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "PROD-006",
                            Descripcion = "USB 3.0, Portátil, Negro",
                            Nombre = "Disco Duro Externo 1TB"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "PROD-007",
                            Descripcion = "USB 3.0, Alta velocidad",
                            Nombre = "Memoria USB 32GB Kingston"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "PROD-008",
                            Descripcion = "720p, USB, Micrófono integrado",
                            Nombre = "Webcam Logitech C270"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "PROD-009",
                            Descripcion = "1080p, Compatible 4K",
                            Nombre = "Cable HDMI 2m"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "PROD-010",
                            Descripcion = "USB 3.0, Alimentación externa",
                            Nombre = "Hub USB 4 puertos"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.Lote", b =>
                {
                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
